### ISSUE TITLE
🐾 

### ISSUE THREAD

**Issue by ChandanPolai** [onamkrverma/nextjs-portfolio#81]
🚀 **Hey Onam,**

✨ First of all, I want to say that your portfolio project is **impressive**! The design, functionality, and attention to detail really stand out and reflect your skills. 👏

💡 I've recently copied your portfolio repo to make some changes, but I'm facing a few difficulties with the modifications. I'd love to discuss these changes with you and get some guidance if possible. Your insights would be incredibly helpful. 🙌

📞 Please feel free to contact me at **+91 7069472565** or reply here whenever you can. 

Looking forward to connecting! 🤝

**Best regards,**  
Chandan

**Comment by onamkrverma** [comment]
Hi @ChandanPolai,
Could you please let me know what difficulties you're encountering with this Next.js portfolio code?

**Comment by ChandanPolai** [comment]
Yes bro can you provide your mb no 🙏

**Comment by onamkrverma** [comment]
you can dm me screenshot of error on LinkedIn [onamkumarverma](https://www.linkedin.com/in/onamkumarverma/) 
or attach screenshots here in comments

**Comment by ChandanPolai** [comment]
Ok 🆗 my brother no worry I have created another repo and successfully created my portfolio
